### ISSUE TITLE
Piwik event tracking

### ISSUE THREAD

**Issue by c3o** [hack4vdb/anthill-backend#50]
To measure conversion, bounce rates, viral factor etc.

**Comment by PeterTheOne** [comment]
@lutoma Du meintest es gibt eine Piwik instance?

**Comment by lutoma** [comment]
@PeterTheOne  Ja, Logindaten hatte ich im Slack gepostet: https://hack4vdb.slack.com/archives/anthill/p1471281434000314 :100:

**Comment by PeterTheOne** [comment]
added piwik tracking code in https://github.com/hack4vdb/anthill-backend/commit/88ddaee8b7c4cd5965d7111e6ca5e5d4a40761e4

We can also:
- [ ] Add opt-out, see: https://github.com/hack4vdb/anthill-backend/issues/27#issuecomment-240386543
- [x] Config goals?
- [ ] custom variables? etc. https://pythonhosted.org/django-analytical/services/piwik.html#user-variables
- [ ] Add email tracking with image?

**Comment by lutoma** [comment]
I guess we should also make sure the piwik tracking only gets included if not in debug mode. Already seeing some tracked visits where the host is "localhost:8000".

**Comment by PeterTheOne** [comment]
I guess https://pythonhosted.org/django-analytical/services/piwik.html would be a better choice for piwiki integration, it also supports not tracking internal IPs.

**Comment by PeterTheOne** [comment]
ok, not tracking localhost anymore. Too bad ANALYTICAL_AUTO_IDENTIFY didn't work.

**Comment by PeterTheOne** [comment]
Ich hab ein Spenden und ein Join Meetup Goal angelegt.
