### ISSUE TITLE
Steps before production

### ISSUE THREAD

**Issue by stefan2904** [hack4vdb/anthill-backend#95]
- [ ] Turn off DEBUG mode in config: https://docs.djangoproject.com/en/1.10/ref/settings/#debug
- [ ] change SECRET_KEY in local config: https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-SECRET_KEY
- [x] Rotate secret for Bot API (check API_KEY in local config) #87
- [x] Rotate (different!) secret for Newsletter API #79
- [ ] configure mail gateway (to use the VDB one?)
- [ ] change database password in local config (and on dbms)
- [ ] reset database, perform full migrate
- [ ] tune logging
- [ ] enable/tune monitoring
- [ ] fail2ban and such
- [ ] disable password protection, see #80

;-)

**Comment by stefan2904** [comment]
(anything else, @MSch @lutoma?)

**Comment by lutoma** [comment]
I'll review the code in the next days before it actually goes live and see if I can find anything.

**Comment by MSch** [comment]
I added the secret rotation for thew Newsletter API #79.

Other than that nothing I can think of.

**Comment by stefan2904** [comment]
@lutoma das müsstest jetzt alles du machen, vmtl Sonntag Abend, geht das klar von dir aus?
